// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_deletions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const finishUserDeletion = `-- name: FinishUserDeletion :exec
DELETE FROM account_deletions WHERE user_id = $1
`

func (q *Queries) FinishUserDeletion(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishUserDeletion, userID)
	return err
}

const markDeletionPublished = `-- name: MarkDeletionPublished :execrows
UPDATE account_deletions
SET published_at = now()
WHERE user_id = $1
  AND published_at IS NULL
`

func (q *Queries) MarkDeletionPublished(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDeletionPublished, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pendingDeletions = `-- name: PendingDeletions :many
SELECT user_id
FROM account_deletions
WHERE published_at IS NULL
ORDER BY requested_at
LIMIT $1
`

func (q *Queries) PendingDeletions(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, pendingDeletions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestUserDeletion = `-- name: RequestUserDeletion :execrows
WITH marked AS (
    UPDATE users
    SET deleted_at = COALESCE(deleted_at, now()),
        updated_at = now()
    WHERE id = $1
    RETURNING id
)
INSERT INTO account_deletions (user_id)
SELECT id FROM marked
ON CONFLICT (user_id) DO UPDATE
SET requested_at = now(),
    published_at = NULL
`

func (q *Queries) RequestUserDeletion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requestUserDeletion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
