// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimAnalysis = `-- name: ClaimAnalysis :one
UPDATE analysis_results
SET status = 'running'
WHERE id = $1 AND status IN ('pending', 'running')
RETURNING id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at
`

// Claims a job for this delivery. Terminal rows return no row, so a redelivered
// job can be acked without scoring the conversation again.
func (q *Queries) ClaimAnalysis(ctx context.Context, id uuid.UUID) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, claimAnalysis, id)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeAnalysis = `-- name: CompleteAnalysis :one
UPDATE analysis_results
SET status = 'succeeded',
    segments = $2,
    overall = $3,
    model_version = $4,
    completed_at = now(),
    error = ''
WHERE id = $1
RETURNING id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at
`

type CompleteAnalysisParams struct {
	ID           uuid.UUID       `json:"id"`
	Segments     json.RawMessage `json:"segments"`
	Overall      json.RawMessage `json:"overall"`
	ModelVersion string          `json:"model_version"`
}

func (q *Queries) CompleteAnalysis(ctx context.Context, arg CompleteAnalysisParams) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, completeAnalysis,
		arg.ID,
		arg.Segments,
		arg.Overall,
		arg.ModelVersion,
	)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAnalysisResult = `-- name: CreateAnalysisResult :one
INSERT INTO analysis_results (conversation_id, status)
VALUES ($1, 'pending')
RETURNING id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at
`

func (q *Queries) CreateAnalysisResult(ctx context.Context, conversationID uuid.UUID) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, createAnalysisResult, conversationID)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title, platform, match_name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, platform, match_name, created_at
`

type CreateConversationParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Platform  string    `json:"platform"`
	MatchName string    `json:"match_name"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.UserID,
		arg.Title,
		arg.Platform,
		arg.MatchName,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Platform,
		&i.MatchName,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, position, sender, body, sent_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversation_id, position, sender, body, sent_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Position       int32     `json:"position"`
	Sender         string    `json:"sender"`
	Body           string    `json:"body"`
	SentAt         time.Time `json:"sent_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Position,
		arg.Sender,
		arg.Body,
		arg.SentAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Position,
		&i.Sender,
		&i.Body,
		&i.SentAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, kind, payload)
VALUES ($1, $2, $3)
RETURNING id, user_id, kind, payload, sent_at, created_at
`

type CreateNotificationParams struct {
	UserID  uuid.UUID       `json:"user_id"`
	Kind    string          `json:"kind"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Kind, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Payload,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const failAnalysis = `-- name: FailAnalysis :one
UPDATE analysis_results
SET status = 'failed',
    error = $2,
    completed_at = now()
WHERE id = $1
RETURNING id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at
`

type FailAnalysisParams struct {
	ID    uuid.UUID `json:"id"`
	Error string    `json:"error"`
}

func (q *Queries) FailAnalysis(ctx context.Context, arg FailAnalysisParams) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, failAnalysis, arg.ID, arg.Error)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAnalysisResult = `-- name: GetAnalysisResult :one
SELECT id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at FROM analysis_results WHERE id = $1
`

func (q *Queries) GetAnalysisResult(ctx context.Context, id uuid.UUID) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, getAnalysisResult, id)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, platform, match_name, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Platform,
		&i.MatchName,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAnalysisForConversation = `-- name: GetLatestAnalysisForConversation :one
SELECT id, conversation_id, status, model_version, segments, overall, error, created_at, completed_at FROM analysis_results
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAnalysisForConversation(ctx context.Context, conversationID uuid.UUID) (AnalysisResult, error) {
	row := q.db.QueryRow(ctx, getLatestAnalysisForConversation, conversationID)
	var i AnalysisResult
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.ModelVersion,
		&i.Segments,
		&i.Overall,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT id, user_id, title, platform, match_name, created_at FROM conversations
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Platform,
			&i.MatchName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, position, sender, body, sent_at FROM messages
WHERE conversation_id = $1
ORDER BY position
`

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Position,
			&i.Sender,
			&i.Body,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingExamples = `-- name: ListTrainingExamples :many
SELECT id, conversation_id, label_source, outcome, reply_received, engagement_score, segment_labels, notes, consented, created_at FROM training_examples
WHERE consented
ORDER BY created_at
LIMIT $1 OFFSET $2
`

type ListTrainingExamplesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrainingExamples(ctx context.Context, arg ListTrainingExamplesParams) ([]TrainingExample, error) {
	rows, err := q.db.Query(ctx, listTrainingExamples, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingExample{}
	for rows.Next() {
		var i TrainingExample
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.LabelSource,
			&i.Outcome,
			&i.ReplyReceived,
			&i.EngagementScore,
			&i.SegmentLabels,
			&i.Notes,
			&i.Consented,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications SET sent_at = now() WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const upsertTrainingExample = `-- name: UpsertTrainingExample :one
INSERT INTO training_examples (conversation_id, label_source, outcome, reply_received, engagement_score, segment_labels, notes, consented)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (conversation_id, label_source) DO UPDATE
SET outcome = EXCLUDED.outcome,
    reply_received = EXCLUDED.reply_received,
    engagement_score = EXCLUDED.engagement_score,
    segment_labels = EXCLUDED.segment_labels,
    notes = EXCLUDED.notes,
    consented = EXCLUDED.consented
RETURNING id, conversation_id, label_source, outcome, reply_received, engagement_score, segment_labels, notes, consented, created_at
`

type UpsertTrainingExampleParams struct {
	ConversationID  uuid.UUID       `json:"conversation_id"`
	LabelSource     string          `json:"label_source"`
	Outcome         *string         `json:"outcome"`
	ReplyReceived   *bool           `json:"reply_received"`
	EngagementScore *float64        `json:"engagement_score"`
	SegmentLabels   json.RawMessage `json:"segment_labels"`
	Notes           string          `json:"notes"`
	Consented       bool            `json:"consented"`
}

func (q *Queries) UpsertTrainingExample(ctx context.Context, arg UpsertTrainingExampleParams) (TrainingExample, error) {
	row := q.db.QueryRow(ctx, upsertTrainingExample,
		arg.ConversationID,
		arg.LabelSource,
		arg.Outcome,
		arg.ReplyReceived,
		arg.EngagementScore,
		arg.SegmentLabels,
		arg.Notes,
		arg.Consented,
	)
	var i TrainingExample
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.LabelSource,
		&i.Outcome,
		&i.ReplyReceived,
		&i.EngagementScore,
		&i.SegmentLabels,
		&i.Notes,
		&i.Consented,
		&i.CreatedAt,
	)
	return i, err
}
