// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeChatThread = `-- name: CloseChatThread :one
UPDATE chat_threads SET status = 'closed' WHERE id = $1 RETURNING id, user_id, coach_id, session_id, status, created_at, last_message_at
`

func (q *Queries) CloseChatThread(ctx context.Context, id uuid.UUID) (ChatThread, error) {
	row := q.db.QueryRow(ctx, closeChatThread, id)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (thread_id, sender_id, body)
VALUES ($1, $2, $3)
RETURNING id, thread_id, sender_id, body, created_at
`

type CreateChatMessageParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Body     string    `json:"body"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.ThreadID, arg.SenderID, arg.Body)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createChatThread = `-- name: CreateChatThread :one
INSERT INTO chat_threads (user_id, coach_id, session_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, coach_id, session_id, status, created_at, last_message_at
`

type CreateChatThreadParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	CoachID   uuid.UUID  `json:"coach_id"`
	SessionID *uuid.UUID `json:"session_id"`
}

func (q *Queries) CreateChatThread(ctx context.Context, arg CreateChatThreadParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, createChatThread, arg.UserID, arg.CoachID, arg.SessionID)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getActiveThreadForPair = `-- name: GetActiveThreadForPair :one
SELECT id, user_id, coach_id, session_id, status, created_at, last_message_at FROM chat_threads
WHERE user_id = $1 AND coach_id = $2 AND status = 'active'
ORDER BY last_message_at DESC
LIMIT 1
`

type GetActiveThreadForPairParams struct {
	UserID  uuid.UUID `json:"user_id"`
	CoachID uuid.UUID `json:"coach_id"`
}

func (q *Queries) GetActiveThreadForPair(ctx context.Context, arg GetActiveThreadForPairParams) (ChatThread, error) {
	row := q.db.QueryRow(ctx, getActiveThreadForPair, arg.UserID, arg.CoachID)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getChatThread = `-- name: GetChatThread :one
SELECT id, user_id, coach_id, session_id, status, created_at, last_message_at FROM chat_threads WHERE id = $1
`

func (q *Queries) GetChatThread(ctx context.Context, id uuid.UUID) (ChatThread, error) {
	row := q.db.QueryRow(ctx, getChatThread, id)
	var i ChatThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.SessionID,
		&i.Status,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, thread_id, sender_id, body, created_at FROM chat_messages
WHERE thread_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChatMessagesParams struct {
	ThreadID uuid.UUID `json:"thread_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.ThreadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForCoach = `-- name: ListThreadsForCoach :many
SELECT t.id, t.user_id, t.coach_id, t.session_id, t.status, t.created_at, t.last_message_at, u.display_name AS counterpart_name
FROM chat_threads t
JOIN users u ON u.id = t.user_id
WHERE t.coach_id = $1
  AND ($2::text IS NULL OR t.status = $2::text)
ORDER BY t.last_message_at DESC
`

type ListThreadsForCoachParams struct {
	CoachID uuid.UUID `json:"coach_id"`
	Status  *string   `json:"status"`
}

type ListThreadsForCoachRow struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	CoachID         uuid.UUID  `json:"coach_id"`
	SessionID       *uuid.UUID `json:"session_id"`
	Status          string     `json:"status"`
	CreatedAt       time.Time  `json:"created_at"`
	LastMessageAt   time.Time  `json:"last_message_at"`
	CounterpartName string     `json:"counterpart_name"`
}

func (q *Queries) ListThreadsForCoach(ctx context.Context, arg ListThreadsForCoachParams) ([]ListThreadsForCoachRow, error) {
	rows, err := q.db.Query(ctx, listThreadsForCoach, arg.CoachID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsForCoachRow{}
	for rows.Next() {
		var i ListThreadsForCoachRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CoachID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.CounterpartName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForUser = `-- name: ListThreadsForUser :many
SELECT t.id, t.user_id, t.coach_id, t.session_id, t.status, t.created_at, t.last_message_at, u.display_name AS counterpart_name
FROM chat_threads t
JOIN users u ON u.id = t.coach_id
WHERE t.user_id = $1
ORDER BY t.last_message_at DESC
`

type ListThreadsForUserRow struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	CoachID         uuid.UUID  `json:"coach_id"`
	SessionID       *uuid.UUID `json:"session_id"`
	Status          string     `json:"status"`
	CreatedAt       time.Time  `json:"created_at"`
	LastMessageAt   time.Time  `json:"last_message_at"`
	CounterpartName string     `json:"counterpart_name"`
}

func (q *Queries) ListThreadsForUser(ctx context.Context, userID uuid.UUID) ([]ListThreadsForUserRow, error) {
	rows, err := q.db.Query(ctx, listThreadsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsForUserRow{}
	for rows.Next() {
		var i ListThreadsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CoachID,
			&i.SessionID,
			&i.Status,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.CounterpartName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatThread = `-- name: TouchChatThread :exec
UPDATE chat_threads SET last_message_at = now() WHERE id = $1
`

func (q *Queries) TouchChatThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchChatThread, id)
	return err
}
