// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: coaching.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCoachAvailability = `-- name: AddCoachAvailability :one
INSERT INTO coach_availability (coach_id, weekday, start_minute, end_minute)
VALUES ($1, $2, $3, $4)
RETURNING id, coach_id, weekday, start_minute, end_minute
`

type AddCoachAvailabilityParams struct {
	CoachID     uuid.UUID `json:"coach_id"`
	Weekday     int16     `json:"weekday"`
	StartMinute int32     `json:"start_minute"`
	EndMinute   int32     `json:"end_minute"`
}

func (q *Queries) AddCoachAvailability(ctx context.Context, arg AddCoachAvailabilityParams) (CoachAvailability, error) {
	row := q.db.QueryRow(ctx, addCoachAvailability,
		arg.CoachID,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
	)
	var i CoachAvailability
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Weekday,
		&i.StartMinute,
		&i.EndMinute,
	)
	return i, err
}

const createCoachingSession = `-- name: CreateCoachingSession :one
INSERT INTO coaching_sessions (user_id, coach_id, scheduled_time, duration_minutes, topic)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, coach_id, scheduled_time, duration_minutes, status, topic, coach_notes, created_at, updated_at
`

type CreateCoachingSessionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	CoachID         uuid.UUID `json:"coach_id"`
	ScheduledTime   time.Time `json:"scheduled_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	Topic           string    `json:"topic"`
}

func (q *Queries) CreateCoachingSession(ctx context.Context, arg CreateCoachingSessionParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, createCoachingSession,
		arg.UserID,
		arg.CoachID,
		arg.ScheduledTime,
		arg.DurationMinutes,
		arg.Topic,
	)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.ScheduledTime,
		&i.DurationMinutes,
		&i.Status,
		&i.Topic,
		&i.CoachNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoach = `-- name: GetCoach :one
SELECT c.user_id, c.headline, c.bio, c.specialties, c.hourly_rate_cents, c.timezone, c.years_experience, c.accepting_clients, c.created_at, c.updated_at, u.display_name, u.email
FROM coaches c
JOIN users u ON u.id = c.user_id
WHERE c.user_id = $1
`

type GetCoachRow struct {
	UserID           uuid.UUID `json:"user_id"`
	Headline         string    `json:"headline"`
	Bio              string    `json:"bio"`
	Specialties      []string  `json:"specialties"`
	HourlyRateCents  int32     `json:"hourly_rate_cents"`
	Timezone         string    `json:"timezone"`
	YearsExperience  int32     `json:"years_experience"`
	AcceptingClients bool      `json:"accepting_clients"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
}

func (q *Queries) GetCoach(ctx context.Context, userID uuid.UUID) (GetCoachRow, error) {
	row := q.db.QueryRow(ctx, getCoach, userID)
	var i GetCoachRow
	err := row.Scan(
		&i.UserID,
		&i.Headline,
		&i.Bio,
		&i.Specialties,
		&i.HourlyRateCents,
		&i.Timezone,
		&i.YearsExperience,
		&i.AcceptingClients,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const getCoachingSession = `-- name: GetCoachingSession :one
SELECT id, user_id, coach_id, scheduled_time, duration_minutes, status, topic, coach_notes, created_at, updated_at FROM coaching_sessions WHERE id = $1
`

func (q *Queries) GetCoachingSession(ctx context.Context, id uuid.UUID) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, getCoachingSession, id)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.ScheduledTime,
		&i.DurationMinutes,
		&i.Status,
		&i.Topic,
		&i.CoachNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookedSlots = `-- name: ListBookedSlots :many
SELECT scheduled_time, duration_minutes
FROM coaching_sessions
WHERE coach_id = $1
  AND status = 'scheduled'
  AND scheduled_time >= $2
  AND scheduled_time < $3
ORDER BY scheduled_time
`

type ListBookedSlotsParams struct {
	CoachID         uuid.UUID `json:"coach_id"`
	ScheduledTime   time.Time `json:"scheduled_time"`
	ScheduledTime_2 time.Time `json:"scheduled_time_2"`
}

type ListBookedSlotsRow struct {
	ScheduledTime   time.Time `json:"scheduled_time"`
	DurationMinutes int32     `json:"duration_minutes"`
}

func (q *Queries) ListBookedSlots(ctx context.Context, arg ListBookedSlotsParams) ([]ListBookedSlotsRow, error) {
	rows, err := q.db.Query(ctx, listBookedSlots, arg.CoachID, arg.ScheduledTime, arg.ScheduledTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookedSlotsRow{}
	for rows.Next() {
		var i ListBookedSlotsRow
		if err := rows.Scan(&i.ScheduledTime, &i.DurationMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoachAvailability = `-- name: ListCoachAvailability :many
SELECT id, coach_id, weekday, start_minute, end_minute FROM coach_availability
WHERE coach_id = $1
ORDER BY weekday, start_minute
`

func (q *Queries) ListCoachAvailability(ctx context.Context, coachID uuid.UUID) ([]CoachAvailability, error) {
	rows, err := q.db.Query(ctx, listCoachAvailability, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoachAvailability{}
	for rows.Next() {
		var i CoachAvailability
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Weekday,
			&i.StartMinute,
			&i.EndMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoaches = `-- name: ListCoaches :many
SELECT c.user_id, c.headline, c.bio, c.specialties, c.hourly_rate_cents, c.timezone, c.years_experience, c.accepting_clients, c.created_at, c.updated_at, u.display_name, u.email
FROM coaches c
JOIN users u ON u.id = c.user_id
WHERE ($3::boolean IS NOT TRUE OR c.accepting_clients)
ORDER BY c.years_experience DESC, u.display_name
LIMIT $1 OFFSET $2
`

type ListCoachesParams struct {
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
	AcceptingOnly *bool `json:"accepting_only"`
}

type ListCoachesRow struct {
	UserID           uuid.UUID `json:"user_id"`
	Headline         string    `json:"headline"`
	Bio              string    `json:"bio"`
	Specialties      []string  `json:"specialties"`
	HourlyRateCents  int32     `json:"hourly_rate_cents"`
	Timezone         string    `json:"timezone"`
	YearsExperience  int32     `json:"years_experience"`
	AcceptingClients bool      `json:"accepting_clients"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	DisplayName      string    `json:"display_name"`
	Email            string    `json:"email"`
}

func (q *Queries) ListCoaches(ctx context.Context, arg ListCoachesParams) ([]ListCoachesRow, error) {
	rows, err := q.db.Query(ctx, listCoaches, arg.Limit, arg.Offset, arg.AcceptingOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoachesRow{}
	for rows.Next() {
		var i ListCoachesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Headline,
			&i.Bio,
			&i.Specialties,
			&i.HourlyRateCents,
			&i.Timezone,
			&i.YearsExperience,
			&i.AcceptingClients,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForCoach = `-- name: ListSessionsForCoach :many
SELECT s.id, s.user_id, s.coach_id, s.scheduled_time, s.duration_minutes, s.status, s.topic, s.coach_notes, s.created_at, s.updated_at, u.display_name AS user_name
FROM coaching_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.coach_id = $1
  AND ($2::text IS NULL OR s.status = $2::text)
  AND ($3::timestamptz IS NULL OR s.scheduled_time >= $3::timestamptz)
ORDER BY s.scheduled_time
`

type ListSessionsForCoachParams struct {
	CoachID  uuid.UUID  `json:"coach_id"`
	Status   *string    `json:"status"`
	FromTime *time.Time `json:"from_time"`
}

type ListSessionsForCoachRow struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CoachID         uuid.UUID `json:"coach_id"`
	ScheduledTime   time.Time `json:"scheduled_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	Status          string    `json:"status"`
	Topic           string    `json:"topic"`
	CoachNotes      string    `json:"coach_notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	UserName        string    `json:"user_name"`
}

func (q *Queries) ListSessionsForCoach(ctx context.Context, arg ListSessionsForCoachParams) ([]ListSessionsForCoachRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForCoach, arg.CoachID, arg.Status, arg.FromTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForCoachRow{}
	for rows.Next() {
		var i ListSessionsForCoachRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CoachID,
			&i.ScheduledTime,
			&i.DurationMinutes,
			&i.Status,
			&i.Topic,
			&i.CoachNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT s.id, s.user_id, s.coach_id, s.scheduled_time, s.duration_minutes, s.status, s.topic, s.coach_notes, s.created_at, s.updated_at, u.display_name AS coach_name
FROM coaching_sessions s
JOIN users u ON u.id = s.coach_id
WHERE s.user_id = $1
  AND ($2::text IS NULL OR s.status = $2::text)
ORDER BY s.scheduled_time
`

type ListSessionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status *string   `json:"status"`
}

type ListSessionsForUserRow struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CoachID         uuid.UUID `json:"coach_id"`
	ScheduledTime   time.Time `json:"scheduled_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	Status          string    `json:"status"`
	Topic           string    `json:"topic"`
	CoachNotes      string    `json:"coach_notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	CoachName       string    `json:"coach_name"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]ListSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForUserRow{}
	for rows.Next() {
		var i ListSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CoachID,
			&i.ScheduledTime,
			&i.DurationMinutes,
			&i.Status,
			&i.Topic,
			&i.CoachNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoachName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCoachAvailability = `-- name: ReplaceCoachAvailability :exec
DELETE FROM coach_availability WHERE coach_id = $1
`

func (q *Queries) ReplaceCoachAvailability(ctx context.Context, coachID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceCoachAvailability, coachID)
	return err
}

const rescheduleSession = `-- name: RescheduleSession :one
UPDATE coaching_sessions
SET scheduled_time = $2, updated_at = now()
WHERE id = $1 AND status = 'scheduled'
RETURNING id, user_id, coach_id, scheduled_time, duration_minutes, status, topic, coach_notes, created_at, updated_at
`

type RescheduleSessionParams struct {
	ID            uuid.UUID `json:"id"`
	ScheduledTime time.Time `json:"scheduled_time"`
}

func (q *Queries) RescheduleSession(ctx context.Context, arg RescheduleSessionParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, rescheduleSession, arg.ID, arg.ScheduledTime)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.ScheduledTime,
		&i.DurationMinutes,
		&i.Status,
		&i.Topic,
		&i.CoachNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionNotes = `-- name: UpdateSessionNotes :one
UPDATE coaching_sessions
SET coach_notes = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, coach_id, scheduled_time, duration_minutes, status, topic, coach_notes, created_at, updated_at
`

type UpdateSessionNotesParams struct {
	ID         uuid.UUID `json:"id"`
	CoachNotes string    `json:"coach_notes"`
}

func (q *Queries) UpdateSessionNotes(ctx context.Context, arg UpdateSessionNotesParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, updateSessionNotes, arg.ID, arg.CoachNotes)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.ScheduledTime,
		&i.DurationMinutes,
		&i.Status,
		&i.Topic,
		&i.CoachNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE coaching_sessions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, coach_id, scheduled_time, duration_minutes, status, topic, coach_notes, created_at, updated_at
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (CoachingSession, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status)
	var i CoachingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CoachID,
		&i.ScheduledTime,
		&i.DurationMinutes,
		&i.Status,
		&i.Topic,
		&i.CoachNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachProfile = `-- name: UpsertCoachProfile :one
INSERT INTO coaches (user_id, headline, bio, specialties, hourly_rate_cents, timezone, years_experience, accepting_clients)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE
SET headline = EXCLUDED.headline,
    bio = EXCLUDED.bio,
    specialties = EXCLUDED.specialties,
    hourly_rate_cents = EXCLUDED.hourly_rate_cents,
    timezone = EXCLUDED.timezone,
    years_experience = EXCLUDED.years_experience,
    accepting_clients = EXCLUDED.accepting_clients,
    updated_at = now()
RETURNING user_id, headline, bio, specialties, hourly_rate_cents, timezone, years_experience, accepting_clients, created_at, updated_at
`

type UpsertCoachProfileParams struct {
	UserID           uuid.UUID `json:"user_id"`
	Headline         string    `json:"headline"`
	Bio              string    `json:"bio"`
	Specialties      []string  `json:"specialties"`
	HourlyRateCents  int32     `json:"hourly_rate_cents"`
	Timezone         string    `json:"timezone"`
	YearsExperience  int32     `json:"years_experience"`
	AcceptingClients bool      `json:"accepting_clients"`
}

func (q *Queries) UpsertCoachProfile(ctx context.Context, arg UpsertCoachProfileParams) (Coach, error) {
	row := q.db.QueryRow(ctx, upsertCoachProfile,
		arg.UserID,
		arg.Headline,
		arg.Bio,
		arg.Specialties,
		arg.HourlyRateCents,
		arg.Timezone,
		arg.YearsExperience,
		arg.AcceptingClients,
	)
	var i Coach
	err := row.Scan(
		&i.UserID,
		&i.Headline,
		&i.Bio,
		&i.Specialties,
		&i.HourlyRateCents,
		&i.Timezone,
		&i.YearsExperience,
		&i.AcceptingClients,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
