// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countExhaustedEmails = `-- name: CountExhaustedEmails :one
SELECT count(*) FROM email_outbox
WHERE sent_at IS NULL AND attempts >= $1
`

func (q *Queries) CountExhaustedEmails(ctx context.Context, attempts int32) (int64, error) {
	row := q.db.QueryRow(ctx, countExhaustedEmails, attempts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueEmail = `-- name: EnqueueEmail :one
INSERT INTO email_outbox (to_email, subject, body, ics)
VALUES ($1, $2, $3, $4)
RETURNING id, to_email, subject, body, ics, attempts, last_error, next_attempt_at, created_at, sent_at
`

type EnqueueEmailParams struct {
	ToEmail string  `json:"to_email"`
	Subject string  `json:"subject"`
	Body    string  `json:"body"`
	Ics     *string `json:"ics"`
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueEmail,
		arg.ToEmail,
		arg.Subject,
		arg.Body,
		arg.Ics,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToEmail,
		&i.Subject,
		&i.Body,
		&i.Ics,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const markEmailFailed = `-- name: MarkEmailFailed :execrows
UPDATE email_outbox
SET attempts = attempts + 1,
    last_error = $2,
    next_attempt_at = now() + $3::interval
WHERE id = $1 AND sent_at IS NULL
`

type MarkEmailFailedParams struct {
	ID         uuid.UUID       `json:"id"`
	LastError  string          `json:"last_error"`
	RetryAfter pgtype.Interval `json:"retry_after"`
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailFailed, arg.ID, arg.LastError, arg.RetryAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailSent = `-- name: MarkEmailSent :execrows
UPDATE email_outbox
SET sent_at = now(), attempts = attempts + 1, last_error = ''
WHERE id = $1 AND sent_at IS NULL
`

func (q *Queries) MarkEmailSent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailSent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pendingEmails = `-- name: PendingEmails :many
SELECT id, to_email, subject, body, ics, attempts, last_error, next_attempt_at, created_at, sent_at FROM email_outbox
WHERE sent_at IS NULL AND attempts < $2 AND next_attempt_at <= now()
ORDER BY next_attempt_at
LIMIT $1
`

type PendingEmailsParams struct {
	Limit    int32 `json:"limit"`
	Attempts int32 `json:"attempts"`
}

func (q *Queries) PendingEmails(ctx context.Context, arg PendingEmailsParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, pendingEmails, arg.Limit, arg.Attempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.Ics,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
