// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AnalysisResult struct {
	ID             uuid.UUID       `json:"id"`
	ConversationID uuid.UUID       `json:"conversation_id"`
	Status         string          `json:"status"`
	ModelVersion   string          `json:"model_version"`
	Segments       json.RawMessage `json:"segments"`
	Overall        json.RawMessage `json:"overall"`
	Error          string          `json:"error"`
	CreatedAt      time.Time       `json:"created_at"`
	CompletedAt    *time.Time      `json:"completed_at"`
}

type ChatMessage struct {
	ID        uuid.UUID `json:"id"`
	ThreadID  uuid.UUID `json:"thread_id"`
	SenderID  uuid.UUID `json:"sender_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type ChatThread struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
	CoachID       uuid.UUID  `json:"coach_id"`
	SessionID     *uuid.UUID `json:"session_id"`
	Status        string     `json:"status"`
	CreatedAt     time.Time  `json:"created_at"`
	LastMessageAt time.Time  `json:"last_message_at"`
}

type Coach struct {
	UserID           uuid.UUID `json:"user_id"`
	Headline         string    `json:"headline"`
	Bio              string    `json:"bio"`
	Specialties      []string  `json:"specialties"`
	HourlyRateCents  int32     `json:"hourly_rate_cents"`
	Timezone         string    `json:"timezone"`
	YearsExperience  int32     `json:"years_experience"`
	AcceptingClients bool      `json:"accepting_clients"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type CoachAvailability struct {
	ID          uuid.UUID `json:"id"`
	CoachID     uuid.UUID `json:"coach_id"`
	Weekday     int16     `json:"weekday"`
	StartMinute int32     `json:"start_minute"`
	EndMinute   int32     `json:"end_minute"`
}

type CoachingSession struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CoachID         uuid.UUID `json:"coach_id"`
	ScheduledTime   time.Time `json:"scheduled_time"`
	DurationMinutes int32     `json:"duration_minutes"`
	Status          string    `json:"status"`
	Topic           string    `json:"topic"`
	CoachNotes      string    `json:"coach_notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Conversation struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Platform  string    `json:"platform"`
	MatchName string    `json:"match_name"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	Position       int32     `json:"position"`
	Sender         string    `json:"sender"`
	Body           string    `json:"body"`
	SentAt         time.Time `json:"sent_at"`
}

type Notification struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	Kind      string          `json:"kind"`
	Payload   json.RawMessage `json:"payload"`
	SentAt    *time.Time      `json:"sent_at"`
	CreatedAt time.Time       `json:"created_at"`
}

type TrainingExample struct {
	ID              uuid.UUID       `json:"id"`
	ConversationID  uuid.UUID       `json:"conversation_id"`
	LabelSource     string          `json:"label_source"`
	Outcome         *string         `json:"outcome"`
	ReplyReceived   *bool           `json:"reply_received"`
	EngagementScore *float64        `json:"engagement_score"`
	SegmentLabels   json.RawMessage `json:"segment_labels"`
	Notes           string          `json:"notes"`
	Consented       bool            `json:"consented"`
	CreatedAt       time.Time       `json:"created_at"`
}

type User struct {
	ID                    uuid.UUID  `json:"id"`
	Email                 string     `json:"email"`
	PasswordHash          string     `json:"password_hash"`
	DisplayName           string     `json:"display_name"`
	Role                  string     `json:"role"`
	EmailVerified         bool       `json:"email_verified"`
	VerificationToken     *string    `json:"verification_token"`
	VerificationExpiresAt *time.Time `json:"verification_expires_at"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}
