// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revocations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredRevocations = `-- name: DeleteExpiredRevocations :execrows
DELETE FROM revoked_sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredRevocations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRevocations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isSessionRevoked = `-- name: IsSessionRevoked :one
SELECT EXISTS (
    SELECT 1 FROM revoked_sessions WHERE user_id = $1 AND expires_at > now()
)
`

func (q *Queries) IsSessionRevoked(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionRevoked, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
INSERT INTO revoked_sessions (user_id, expires_at)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET revoked_at = now(),
    expires_at = GREATEST(revoked_sessions.expires_at, EXCLUDED.expires_at)
`

type RevokeUserSessionsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.UserID, arg.ExpiresAt)
	return err
}
