// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, role, verification_token, verification_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, display_name, role, email_verified, verification_token, verification_expires_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email                 string     `json:"email"`
	PasswordHash          string     `json:"password_hash"`
	DisplayName           string     `json:"display_name"`
	Role                  string     `json:"role"`
	VerificationToken     *string    `json:"verification_token"`
	VerificationExpiresAt *time.Time `json:"verification_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.VerificationToken,
		arg.VerificationExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, role, email_verified, verification_token, verification_expires_at, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, role, email_verified, verification_token, verification_expires_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users
SET verification_token = $2,
    verification_expires_at = $3,
    updated_at = now()
WHERE id = $1
`

type SetVerificationTokenParams struct {
	ID                    uuid.UUID  `json:"id"`
	VerificationToken     *string    `json:"verification_token"`
	VerificationExpiresAt *time.Time `json:"verification_expires_at"`
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.ID, arg.VerificationToken, arg.VerificationExpiresAt)
	return err
}

const userRowExists = `-- name: UserRowExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserRowExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userRowExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified = true,
    verification_token = NULL,
    verification_expires_at = NULL,
    updated_at = now()
WHERE verification_token = $1
  AND verification_expires_at > now()
  AND deleted_at IS NULL
RETURNING id, email, password_hash, display_name, role, email_verified, verification_token, verification_expires_at, created_at, updated_at, deleted_at
`

func (q *Queries) VerifyUserEmail(ctx context.Context, verificationToken *string) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
